# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

cache:
  pip: true

install: pip install tox

script: tox

notifications:
  email: false

python:
  - 3.6
# - 3.7  # Planned: 2018-06
