# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

cache:
  pip: true

install: 
  - pip install check-manifest pytest flake8 readme_renderer
  - pip install numpy numba

script: 
  - check-manifest --ignore tests*
  - python setup.py check -m -r -s
  - flake8 .
  - pytest tests

notifications:
  email: false

python:
  - "3.6"
  - "3.7"
